# Loosely based on https://github.com/manubot/rootstock/blob/1780fac0ac6bba1260a9da3886061730fa5d2765/ci/install.sh
language: minimal

notifications:
  email: false

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-py37_4.8.2-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source $HOME/miniconda/etc/profile.d/conda.sh
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda env create --quiet --file env/minimal-environment.yml
  - conda list --name prmf
  - conda activate prmf

install:
  - pip install portray==1.3.1
  - pip install .
  # Use Manubot portray docs deploy script
  # Include this in repository with attribution if it works well
  - wget https://github.com/manubot/manubot/blob/a4c826ceb954635810ba204a2393dce6fa7a5d5a/ci/deploy-docs.sh

script:
  - python -c "import prmf"
    # See https://github.com/manubot/manubot/blob/a4c826ceb954635810ba204a2393dce6fa7a5d5a/.travis.yml#L23
  - export PYTHONPATH=.
  - portray as_html --overwrite --output_dir=docs

# Deploy procedure from Manubot
# https://github.com/manubot/manubot/blob/a4c826ceb954635810ba204a2393dce6fa7a5d5a/.travis.yml
deploy:
  - provider: script
    script: bash deploy-docs.sh
    skip_cleanup: true
    on:
      repo: manubot/manubot
      branch: master
      condition: $TRAVIS_EVENT_TYPE = "push"
