package:
  name: factorlib
  version: "0.1"

source:
  path: ./

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - factorlib

about:
  license: MIT
  license_file: LICENSE
